<?php

namespace BMG\gestBundle\Repository;

/**
 * OuvrageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuvrageRepository extends \Doctrine\ORM\EntityRepository
{
}
