<?php

namespace BMG\gestBundle\Repository;

/**
 * PretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PretRepository extends \Doctrine\ORM\EntityRepository
{
}
