bmg_gest_home:
    path:     /
    defaults: { _controller: BMGgestBundle:Default:index }

bmg_lister_genres:
    path: /listerGenres
    defaults:
        _controller: BMGgestBundle:gererGenres:index
        
bmg_ajouter_genre:
    path: /ajouterGenre
    defaults:
        _controller: BMGgestBundle:gererGenres:ajouter
        
bmg_consulter_genre:
    path: /consulterGenre/{id}
    defaults:
        _controller: BMGgestBundle:gererGenres:consulter
        id: 000
        
bmg_modifier_genre:
    path: /modifierGenre/{id}
    defaults:
        _controller: BMGgestBundle:gererGenres:modifier
        id: 000
        
bmg_supprimer_genre:
    path: /supprimerGenre/{id}
    defaults:
        _controller: BMGgestBundle:gererGenres:supprimer
        id: 000